// <auto-generated />
using LinqBuild.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LinqBuild.Migrations
{
    [DbContext(typeof(SchoolContext))]
    [Migration("20240502133557_InitiliazDb")]
    partial class InitiliazDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LinqBuild.Models.Class", b =>
                {
                    b.Property<int>("ClassId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClassId"));

                    b.Property<string>("ClassName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TeacherId")
                        .HasColumnType("int");

                    b.HasKey("ClassId");

                    b.HasIndex("TeacherId");

                    b.ToTable("Classes");

                    b.HasData(
                        new
                        {
                            ClassId = 1,
                            ClassName = "Class 1",
                            TeacherId = 1
                        },
                        new
                        {
                            ClassId = 2,
                            ClassName = "Class 2",
                            TeacherId = 2
                        },
                        new
                        {
                            ClassId = 3,
                            ClassName = "Class 3",
                            TeacherId = 3
                        },
                        new
                        {
                            ClassId = 4,
                            ClassName = "Class 4",
                            TeacherId = 4
                        },
                        new
                        {
                            ClassId = 5,
                            ClassName = "Class 5",
                            TeacherId = 5
                        },
                        new
                        {
                            ClassId = 6,
                            ClassName = "Class 6",
                            TeacherId = 6
                        });
                });

            modelBuilder.Entity("LinqBuild.Models.Course", b =>
                {
                    b.Property<int>("CourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CourseId"));

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CourseId");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            CourseId = 1,
                            CourseName = "Backend"
                        },
                        new
                        {
                            CourseId = 2,
                            CourseName = "Frontend"
                        },
                        new
                        {
                            CourseId = 3,
                            CourseName = "OOP"
                        });
                });

            modelBuilder.Entity("LinqBuild.Models.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentId"));

                    b.Property<int>("ClassId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StudentId");

                    b.HasIndex("ClassId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            StudentId = 1,
                            ClassId = 2,
                            Name = "James Smith"
                        },
                        new
                        {
                            StudentId = 2,
                            ClassId = 3,
                            Name = "Maria Garcia"
                        },
                        new
                        {
                            StudentId = 3,
                            ClassId = 4,
                            Name = "Robert Johnson"
                        },
                        new
                        {
                            StudentId = 4,
                            ClassId = 5,
                            Name = "Sophia Martinez"
                        },
                        new
                        {
                            StudentId = 5,
                            ClassId = 6,
                            Name = "Michael Brown"
                        },
                        new
                        {
                            StudentId = 6,
                            ClassId = 1,
                            Name = "Linda Taylor"
                        },
                        new
                        {
                            StudentId = 7,
                            ClassId = 2,
                            Name = "William Jones"
                        },
                        new
                        {
                            StudentId = 8,
                            ClassId = 3,
                            Name = "Barbara Wilson"
                        },
                        new
                        {
                            StudentId = 9,
                            ClassId = 4,
                            Name = "Elizabeth Moore"
                        },
                        new
                        {
                            StudentId = 10,
                            ClassId = 5,
                            Name = "David Lee"
                        },
                        new
                        {
                            StudentId = 11,
                            ClassId = 6,
                            Name = "Oscar Howard"
                        },
                        new
                        {
                            StudentId = 12,
                            ClassId = 1,
                            Name = "Edith Singleton"
                        },
                        new
                        {
                            StudentId = 13,
                            ClassId = 2,
                            Name = "Jame Spears"
                        },
                        new
                        {
                            StudentId = 14,
                            ClassId = 3,
                            Name = "Victor Horne"
                        },
                        new
                        {
                            StudentId = 15,
                            ClassId = 4,
                            Name = "Dale Osborn"
                        },
                        new
                        {
                            StudentId = 16,
                            ClassId = 5,
                            Name = "Dominique Hendricks"
                        },
                        new
                        {
                            StudentId = 17,
                            ClassId = 6,
                            Name = "Rodrigo Chen"
                        },
                        new
                        {
                            StudentId = 18,
                            ClassId = 1,
                            Name = "Latoya Barry"
                        },
                        new
                        {
                            StudentId = 19,
                            ClassId = 2,
                            Name = "Joaquin Soto"
                        },
                        new
                        {
                            StudentId = 20,
                            ClassId = 3,
                            Name = "Raymond Donaldson"
                        },
                        new
                        {
                            StudentId = 21,
                            ClassId = 4,
                            Name = "Shari Valenzuela"
                        },
                        new
                        {
                            StudentId = 22,
                            ClassId = 5,
                            Name = "Maude Le"
                        },
                        new
                        {
                            StudentId = 23,
                            ClassId = 6,
                            Name = "Claudine Pruitt"
                        },
                        new
                        {
                            StudentId = 24,
                            ClassId = 1,
                            Name = "Fannie Ferrell"
                        },
                        new
                        {
                            StudentId = 25,
                            ClassId = 2,
                            Name = "Imogene Gilmore"
                        },
                        new
                        {
                            StudentId = 26,
                            ClassId = 3,
                            Name = "Roberto Park"
                        },
                        new
                        {
                            StudentId = 27,
                            ClassId = 4,
                            Name = "Prince Gallegos"
                        },
                        new
                        {
                            StudentId = 28,
                            ClassId = 5,
                            Name = "Colby Bowen"
                        },
                        new
                        {
                            StudentId = 29,
                            ClassId = 6,
                            Name = "Jody Wilkinson"
                        },
                        new
                        {
                            StudentId = 30,
                            ClassId = 1,
                            Name = "Graciela Mendez"
                        });
                });

            modelBuilder.Entity("LinqBuild.Models.StudentCourse", b =>
                {
                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.HasKey("StudentId", "CourseId");

                    b.HasIndex("CourseId");

                    b.ToTable("StudentCourses");

                    b.HasData(
                        new
                        {
                            StudentId = 1,
                            CourseId = 2
                        },
                        new
                        {
                            StudentId = 2,
                            CourseId = 3
                        },
                        new
                        {
                            StudentId = 2,
                            CourseId = 2
                        },
                        new
                        {
                            StudentId = 2,
                            CourseId = 1
                        },
                        new
                        {
                            StudentId = 3,
                            CourseId = 2
                        },
                        new
                        {
                            StudentId = 3,
                            CourseId = 3
                        },
                        new
                        {
                            StudentId = 4,
                            CourseId = 3
                        },
                        new
                        {
                            StudentId = 4,
                            CourseId = 2
                        },
                        new
                        {
                            StudentId = 4,
                            CourseId = 1
                        },
                        new
                        {
                            StudentId = 5,
                            CourseId = 1
                        },
                        new
                        {
                            StudentId = 6,
                            CourseId = 2
                        },
                        new
                        {
                            StudentId = 6,
                            CourseId = 3
                        },
                        new
                        {
                            StudentId = 7,
                            CourseId = 3
                        },
                        new
                        {
                            StudentId = 7,
                            CourseId = 2
                        },
                        new
                        {
                            StudentId = 7,
                            CourseId = 1
                        },
                        new
                        {
                            StudentId = 8,
                            CourseId = 1
                        },
                        new
                        {
                            StudentId = 8,
                            CourseId = 3
                        },
                        new
                        {
                            StudentId = 8,
                            CourseId = 2
                        },
                        new
                        {
                            StudentId = 9,
                            CourseId = 3
                        },
                        new
                        {
                            StudentId = 9,
                            CourseId = 2
                        },
                        new
                        {
                            StudentId = 10,
                            CourseId = 1
                        },
                        new
                        {
                            StudentId = 11,
                            CourseId = 2
                        },
                        new
                        {
                            StudentId = 11,
                            CourseId = 3
                        },
                        new
                        {
                            StudentId = 11,
                            CourseId = 1
                        },
                        new
                        {
                            StudentId = 12,
                            CourseId = 2
                        },
                        new
                        {
                            StudentId = 12,
                            CourseId = 1
                        },
                        new
                        {
                            StudentId = 12,
                            CourseId = 3
                        },
                        new
                        {
                            StudentId = 13,
                            CourseId = 3
                        },
                        new
                        {
                            StudentId = 13,
                            CourseId = 1
                        },
                        new
                        {
                            StudentId = 13,
                            CourseId = 2
                        },
                        new
                        {
                            StudentId = 14,
                            CourseId = 2
                        },
                        new
                        {
                            StudentId = 14,
                            CourseId = 1
                        },
                        new
                        {
                            StudentId = 15,
                            CourseId = 3
                        },
                        new
                        {
                            StudentId = 15,
                            CourseId = 1
                        },
                        new
                        {
                            StudentId = 15,
                            CourseId = 2
                        },
                        new
                        {
                            StudentId = 16,
                            CourseId = 3
                        },
                        new
                        {
                            StudentId = 16,
                            CourseId = 2
                        },
                        new
                        {
                            StudentId = 16,
                            CourseId = 1
                        },
                        new
                        {
                            StudentId = 17,
                            CourseId = 1
                        },
                        new
                        {
                            StudentId = 17,
                            CourseId = 3
                        },
                        new
                        {
                            StudentId = 17,
                            CourseId = 2
                        },
                        new
                        {
                            StudentId = 18,
                            CourseId = 1
                        },
                        new
                        {
                            StudentId = 19,
                            CourseId = 2
                        },
                        new
                        {
                            StudentId = 19,
                            CourseId = 3
                        },
                        new
                        {
                            StudentId = 20,
                            CourseId = 3
                        },
                        new
                        {
                            StudentId = 20,
                            CourseId = 2
                        },
                        new
                        {
                            StudentId = 20,
                            CourseId = 1
                        },
                        new
                        {
                            StudentId = 21,
                            CourseId = 1
                        },
                        new
                        {
                            StudentId = 21,
                            CourseId = 3
                        },
                        new
                        {
                            StudentId = 21,
                            CourseId = 2
                        },
                        new
                        {
                            StudentId = 22,
                            CourseId = 2
                        },
                        new
                        {
                            StudentId = 23,
                            CourseId = 2
                        },
                        new
                        {
                            StudentId = 23,
                            CourseId = 3
                        },
                        new
                        {
                            StudentId = 23,
                            CourseId = 1
                        },
                        new
                        {
                            StudentId = 24,
                            CourseId = 3
                        },
                        new
                        {
                            StudentId = 24,
                            CourseId = 1
                        },
                        new
                        {
                            StudentId = 25,
                            CourseId = 2
                        },
                        new
                        {
                            StudentId = 25,
                            CourseId = 3
                        },
                        new
                        {
                            StudentId = 26,
                            CourseId = 1
                        },
                        new
                        {
                            StudentId = 27,
                            CourseId = 2
                        },
                        new
                        {
                            StudentId = 28,
                            CourseId = 3
                        },
                        new
                        {
                            StudentId = 28,
                            CourseId = 2
                        },
                        new
                        {
                            StudentId = 29,
                            CourseId = 2
                        },
                        new
                        {
                            StudentId = 30,
                            CourseId = 2
                        },
                        new
                        {
                            StudentId = 30,
                            CourseId = 3
                        },
                        new
                        {
                            StudentId = 30,
                            CourseId = 1
                        });
                });

            modelBuilder.Entity("LinqBuild.Models.Teacher", b =>
                {
                    b.Property<int>("TeacherId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TeacherId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TeacherId");

                    b.ToTable("Teachers");

                    b.HasData(
                        new
                        {
                            TeacherId = 1,
                            Name = "Mr. Smith"
                        },
                        new
                        {
                            TeacherId = 2,
                            Name = "Ms. Johnson"
                        },
                        new
                        {
                            TeacherId = 3,
                            Name = "Mr. Clark"
                        },
                        new
                        {
                            TeacherId = 4,
                            Name = "Ms. Davis"
                        },
                        new
                        {
                            TeacherId = 5,
                            Name = "Mr. Brown"
                        },
                        new
                        {
                            TeacherId = 6,
                            Name = "Ms. Miller"
                        });
                });

            modelBuilder.Entity("LinqBuild.Models.TeacherCourse", b =>
                {
                    b.Property<int>("TeacherId")
                        .HasColumnType("int");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.HasKey("TeacherId", "CourseId");

                    b.HasIndex("CourseId");

                    b.ToTable("TeacherCourses");

                    b.HasData(
                        new
                        {
                            TeacherId = 1,
                            CourseId = 2
                        },
                        new
                        {
                            TeacherId = 2,
                            CourseId = 1
                        },
                        new
                        {
                            TeacherId = 3,
                            CourseId = 1
                        },
                        new
                        {
                            TeacherId = 4,
                            CourseId = 2
                        },
                        new
                        {
                            TeacherId = 4,
                            CourseId = 3
                        },
                        new
                        {
                            TeacherId = 5,
                            CourseId = 2
                        },
                        new
                        {
                            TeacherId = 6,
                            CourseId = 3
                        });
                });

            modelBuilder.Entity("LinqBuild.Models.Class", b =>
                {
                    b.HasOne("LinqBuild.Models.Teacher", "Teacher")
                        .WithMany("Classes")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("LinqBuild.Models.Student", b =>
                {
                    b.HasOne("LinqBuild.Models.Class", "Class")
                        .WithMany("Students")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");
                });

            modelBuilder.Entity("LinqBuild.Models.StudentCourse", b =>
                {
                    b.HasOne("LinqBuild.Models.Course", "Course")
                        .WithMany("StudentCourses")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LinqBuild.Models.Student", "Student")
                        .WithMany("StudentCourses")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("LinqBuild.Models.TeacherCourse", b =>
                {
                    b.HasOne("LinqBuild.Models.Course", "Course")
                        .WithMany("TeacherCourses")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LinqBuild.Models.Teacher", "Teacher")
                        .WithMany("TeacherCourses")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("LinqBuild.Models.Class", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("LinqBuild.Models.Course", b =>
                {
                    b.Navigation("StudentCourses");

                    b.Navigation("TeacherCourses");
                });

            modelBuilder.Entity("LinqBuild.Models.Student", b =>
                {
                    b.Navigation("StudentCourses");
                });

            modelBuilder.Entity("LinqBuild.Models.Teacher", b =>
                {
                    b.Navigation("Classes");

                    b.Navigation("TeacherCourses");
                });
#pragma warning restore 612, 618
        }
    }
}
